import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Footer from '../components/Footer'
import axios from 'axios'
import Link from 'next/link'

export default function Home({blog}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>

      <main className={styles.main}>
        {blog.map((item) => {
        return <div key={item.url} className={styles.bloghome}>
            <div className={styles.blogleft}>
            <Link href={item.url} target='blank'>
            <img style={{width:'100%', maxHeight: '200px'}} src={item.imgurl} alt='blog' />
            </Link>
            </div>
            <div className={styles.blogright}>
            <h1>{item.title.substring(0,200)}</h1>
            <code>By <Link href={'/@'+item.username} target='blank'>{item.author.displayName}</Link> on {new Date(item.createdAt).toLocaleTimeString(undefined, { year: "numeric", month: "long", day: "numeric" })}</code><br/><br/>
            <Link href={item.url} target='blank'>
                <button style={{margin:'0px'}}>Read More <i class="fas fa-glasses"></i></button>
            </Link>
            </div>
        </div>
        })}
      </main>
    <Footer/>
    </div>
  )
}

export async function getServerSideProps({params}){
  const req = await axios.get(`/blog`)
  const data =req.data
  return{
    props:{blog : data}
  }
}